SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ilateral\Twitter\Extension\TwitterSiteConfig
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - ilateral\Twitter\Extension\TwitterController
